### PR TITLE
fix #38 by changing a tag to span

### LINKED ISSUE #38: Issue when clicking hackaton in Timeline
**This issue relates to one or more of the following:**

- [x ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**

The page hangs due to data-target="#".

### PR DESCRIPTION
**Pull request by mohitrajane**
fixed by changing a to span and removing href

### CODE REVIEW

**Comment by yedhink** [comment]
@mohitrajane you're behind the fsdc master. Pls pull the latest and merge it and push your code

**Comment by yedhink** [comment]
@mohitrajane whole pr is broken. why did you change the whole nav-bar section? why was the register content removed? Please fix those issues.

**Comment by mohitrajane** [comment]
i did what??

**Comment by yedhink** [comment]
compare your arduino file with the one currently in master.

**Comment by mohitrajane** [comment]
can u check my new pr request should be working

**Pull request closed without merging**
